# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0003_auto_20160712_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='active',
            field=models.DateTimeField(auto_now=True),
        ),
    ]