# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0004_auto_20160712_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commented_to',
        ),
        migrations.AddField(
            model_name='comment',
            name='commented_to_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Forum.Answer'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commented_to_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Forum.Question'),
        ),
    ]